version: "3.8"

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    ports:
      - "3000:5001"
    volumes:
      - open-webui:/app/backend/data

volumes:
  open-webui: